version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: YourStrong@Passw0rd
      DB_NAME: todos_db
      API_KEY: my-secret-key
    depends_on:
      - db
volumes:
  mssql-data:
